### ISSUE TITLE
Some questions about CP

### ISSUE THREAD

**Issue by yuntao-ma** [BierOne/bottom-up-attention-vqa#1]
Thanks for your implementation.  Especially "Add test support and save_results function." helps me a lot.
I have some questions about CP-V1 and CP-V2. 
1. Are they related to VQA V2, or just some other datasets? 
2. I noticed that CP-V1 and CP-V2 only have "train" and "test". What does it mean?

The implementation of hengyuan-hu supports VQA V2, and what about this implementation?
Thanks again.

**Comment by BierOne** [comment]
Hi, yuntao!
1. About VQA-CP datasets, please refer to this link: [VQA-CP](https://www.cc.gatech.edu/~aagrawal307/vqa-cp/) 
2. The VQA-CP datasets only contain two splits, 'train' and 'test', which is different from standard VQA datasets(VQA-v1 & v2). So I have to identify datasets in different ways. About this, you can check [utils.py](). And there's the link of standard datasets: [VQA-v1&v2](https://visualqa.org/download.html)
3. hengyuan-hu's implementation is very good. They spent a lot of time exploring the way to reduce the degree of difficulty and improve performance at the same time. I greatly appreciate that. However, it's version may be old for us, so I updated the code and added some parts that I think we need.

Thanks,
Yibing
