### ISSUE TITLE
ask for preprocessing image feature file 

### ISSUE THREAD

**Issue by beijing1214** [BierOne/bottom-up-attention-vqa#2]
Hi, BierOne. I run your repo relation-vqa which is a perfect work. But unzip the coco dataset and extract features take me a lot time because of my poor computer ability. Would you please send me the processing image feature file? much thanks. you can concat me with qq 328351839 or wx 19994408235（a328351839）

**Comment by BierOne** [comment]
Hi! Thanks for your attention. I’m so sorry for the late response as I was overwhelmed in the last several months. The good thing is that I have extracted genome features several days ago. And if you still need this feature file, please contact me.
