### ISSUE TITLE
The data downloaded website?

### ISSUE THREAD

**Issue by alice-cool** [BierOne/bottom-up-attention-vqa#3]
Is the data from https://github.com/peteanderson80/bottom-up-attention?

**Comment by BierOne** [comment]
Yes, it's from that site. And you can directly preprocess that downloaded tsv file through this [preprocess-image-rcnn.py](https://github.com/BierOne/bottom-up-attention-vqa/blob/master/tools/preprocess-image-rcnn.py).

**Comment by alice-cool** [comment]
I want to run your code smoothly, but run 
```
H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(h5_path, libver='latest') as fd:
Traceback (most recent call last):
  File "/home/anaconda3/envs/vl-bert/lib/python3.6/site-packages/h5py/_hl/files.py", line 199, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '../data/../rcnn-data/trainval_36.h5', errno = 2, error message = 'No such file or directory', flags = 1, o_flags = 2)

During handling of the above exception, another exception occurred:
```
Can you give a Baidu Wanpan or other link to download the lacking datasets(question&answer and faster-rcnn fixed_36)?

**Comment by alice-cool** [comment]
Thank you for your reply, I want to confirm if I should download the shadow blocked three data :
From the https://github.com/peteanderson80/bottom-up-attention to download 

```
36 features per image (fixed):
2014 Train/Val Image Features (120K / 25GB)
2014 Testing Image Features (40K / 9GB)
2015 Testing Image Features (80K / 17GB)

```

And I should run your preprocess-image-rcnn.py. to get the feature?

**Comment by alice-cool** [comment]
If the source of image features of the code is solved, where is the data about question&answer? Can you give the download link?

**Comment by BierOne** [comment]
Sorry, Alice. Baidu Wanpan maybe not suitable to share that large file. 

You are right. You should firstly download that data through peteranderson's link (that you have mentioned). Then run this [preprocess-image-rcnn.py](https://github.com/BierOne/bottom-up-attention-vqa/blob/master/tools/preprocess-image-rcnn.py) to get the h5py-version features. Note that you must edit the config.py to make the directory available for you.

Good luck!

**Comment by BierOne** [comment]
> If the source of image features of the code is solved, where is the data about question&answer? Can you give the download link?

Please refer to this [site](https://visualqa.org/)
