### ISSUE TITLE
the file of tsv is 45.2g(linux) .

### ISSUE THREAD

**Issue by alice-cool** [BierOne/bottom-up-attention-vqa#4]
the size of the tsv of trainval_36 is 45.2g(47437179.kb)。

**Comment by BierOne** [comment]
Hi, Alice. 

This error is commonly known in the community. Please carefully check the error message -- "File exists".
So there's my suggestion: do not create a trainval_36.h5  in the directory.

Regards,
Yibing

**Comment by BierOne** [comment]
=

**Comment by alice-cool** [comment]
In the [preprocess-image-rcnn.py], it has the following two line code    
```
h5_path = config.rcnn_trainval_path if not args.test else config.rcnn_test_path
tsv_path = config.bottom_up_trainval_path if not args.test else config.bottom_up_test_path
```

In the [config.py], because i have the tsv file .So  I modify it as  
```
dataroot = '/home/byd/'
rcnn_output_size = 36  # max number of object proposals per image
bottom_up_trainval_path = dataroot + 'trainval_{}'.format(rcnn_output_size)  # directory containing the .tsv file(s) with bottom up features
```

but I don't have the h5 file,
so  i keep the same as original about h5.
```
main_path = '../data/'
rcnn_path = main_path + '../rcnn-data/'
rcnn_trainval_path = rcnn_path + 'trainval_{}.h5'.format(rcnn_output_size)  # path where preprocessed features from the trainval split are saved to and loaded from
```

Then I run the [preprocess-image-rcnn.py], it has erros :
```
with h5py.File(h5_path, libver='latest') as fd:
Traceback (most recent call last):
  File "/home/anaconda3/envs/vl-bert/lib/python3.6/site-packages/h5py/_hl/files.py", line 199, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '../data/../rcnn-data/trainval_36.h5', errno = 2, error message = 'No such file or directory', flags = 1, o_flags = 2)
```

So I wonder how to get the h5 file ?
if you have answer,please help me, thanks.

**Comment by alice-cool** [comment]
![image](https://user-images.githubusercontent.com/16870890/107939307-807d5200-6fc1-11eb-8e0f-a5fda7ff1fa6.png)
Thanks for your guide! Thanks very much! Happy niu Year

**Comment by alice-cool** [comment]
Hello BierOne,
    Do you know the pretrained faster-rcnn's parameters ' download link? I want to get other features but I want to have the same parameter with the trainval_36.h5 which is from the  pretrained faster-rcnn model.

**Comment by BierOne** [comment]
You can refer to Peteanderson's repository: https://github.com/peteanderson80/bottom-up-attention

**Comment by alice-cool** [comment]
Hello scholar,
&nbsp; &nbsp; &nbsp; &nbsp; I am also interested in the vqa direction.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BierOne"<notifications@github.com&gt;; 
发送时间: 2021年2月15日(星期一) 晚上9:50
收件人: "BierOne/bottom-up-attention-vqa"<bottom-up-attention-vqa@noreply.github.com&gt;; 
抄送: "B202073014 Bi Yan Dong"<2524981200@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [BierOne/bottom-up-attention-vqa] the file of tsv is 45.2g(linux) . (#4)





 
You can refer to Peteanderson's repository: https://github.com/peteanderson80/bottom-up-attention
